name: Conda install

on:
  # Uncomment the below 'push' to trigger on push
  push:
    paths:
      # only run on push for changes to this file
      - .github/workflows/conda.yml
  #  branches:
  #     - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 2 * * WED"
  workflow_dispatch: ~

jobs:
  conda-install:
    name: Install and test
    strategy:
      matrix:
        # NOTE: Re-enable windows-2022 after iimpi libfabric.dll issue fixed.
        # os: [ubuntu-latest, macos-13, macos-14]
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    # This is necessary to ensure conda environment is activated in every step.
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: dolfinx
          create-args: >-
            python=${{ matrix.python-version }}
          cache-downloads: true

      - name: init micromamba for cmd.exe (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          micromamba init -s cmd.exe

      - name: Install DOLFINx with MPICH (Unix-like)
        if: ${{ runner.os != 'Windows' }}
        run: |
          micromamba install -y fenics-dolfinx mpich

      - name: Install DOLFINx (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          micromamba install -y fenics-dolfinx
      
      - name: Test
        if: ${{ runner.os != 'Windows' }}
        run: |
          conda info
          conda list
          mpiexec --version
          mpiexec -v -np 1 python -c "from mpi4py import MPI; import dolfinx; dolfinx.mesh.create_rectangle(comm=MPI.COMM_WORLD, points=((0, 0), (2, 1)), n=(32, 16))"
          mpiexec -v -np 2 python -c "from mpi4py import MPI; import dolfinx; dolfinx.mesh.create_rectangle(comm=MPI.COMM_WORLD, points=((0, 0), (2, 1)), n=(32, 16))"

      - name: Test (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: cmd /C call {0}
        run: |
          echo PATH %PATH%
          micromamba list
          mpiexec --version
          mpiexec -v -np 1 python -c "from mpi4py import MPI; import dolfinx; dolfinx.mesh.create_rectangle(comm=MPI.COMM_WORLD, points=((0, 0), (2, 1)), n=(32, 16))"
          mpiexec -v -np 2 python -c "from mpi4py import MPI; import dolfinx; dolfinx.mesh.create_rectangle(comm=MPI.COMM_WORLD, points=((0, 0), (2, 1)), n=(32, 16))"
